name: Build (Manual)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install Dependencies
      run: npm ci
    - name: Download Library Files
      run: npm run fetch
    - name: Compile and package
      run: npm run dist -- --publish never
      env:
        NODE_OPTIONS: --max-old-space-size=4096
